spring.application.name=catalog-service
server.port=8081
server.shutdown=graceful

######## Catalog Service Configuration  #########
catalog.page-size=10

######## Database Configuration  #########
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false

######## Swagger Configuration  #########
swagger.api-gateway-url=http://localhost:8989/catalog

######## Actuator and Observability Configuration  #########
management.info.git.mode=full
management.tracing.sampling.probability=1.0
#management.endpoints.web.exposure.include=prometheus
#management.endpoint.metrics.enabled=true
#management.endpoint.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]