services:
  baobab-catalog-service:
    image: amuk3lani/baobab-bookstore-catalog-service
    container_name: baobab-catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://baobab-api-gateway:8989/catalog
      - LOGGING_CONFIG
      - JAVA_TOOL_OPTIONS
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_PROTOCOL
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_SERVICE_NAME=inventory-service
      - OTEL_LOGS_EXPORTER
      - OTEL_TRACES_EXPORTER
      - OTEL_METRICS_EXPORTER
      - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
      - OTEL_JAVAAGENT_LOGGING
      - OTEL_JAVAAGENT_ENABLED
      - OTEL_JAVAAGENT_DEBUG
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    volumes:
      - ./deployment/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - my_shared_network
networks:
  my_shared_network:
    name: amu-dev-network
    external: true